# Generated by Django 3.1 on 2020-09-04 12:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inv.models
import inv.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('nip', models.CharField(max_length=10, validators=[inv.validators.nip_validator])),
                ('logo', models.ImageField(blank=True, upload_to=inv.models.user_directory_path)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=25)),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Stanowisko')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('Indywidualny', 'Indywidualny'), ('Biznesowy', 'Biznesowy')], default='Biznesowy', max_length=15, verbose_name='Typ klienta')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa Klienta')),
                ('nip', models.CharField(blank=True, max_length=11, validators=[inv.validators.nip_validator], verbose_name='NIP')),
                ('address', models.CharField(max_length=100, verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Kod poczt.')),
                ('country', models.CharField(max_length=100, verbose_name='Kraj')),
                ('bank_account', models.CharField(blank=True, max_length=25, verbose_name='Konto bankowe')),
                ('regon', models.CharField(blank=True, max_length=20, verbose_name='REGON')),
                ('krs', models.CharField(blank=True, max_length=20, verbose_name='KRS')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Kontakt')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('webpage', models.URLField(blank=True, verbose_name='Strona WWW')),
                ('representation', models.CharField(blank=True, max_length=100, verbose_name='Osoba reprezentująca')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='inv.company')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(choices=[('Pro-Forma', 'Pro-Forma'), ('VAT', 'VAT'), ('Korygująca', 'Korygująca')], max_length=15)),
                ('date_issued', models.DateField(default=datetime.date.today)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('payment_option', models.CharField(blank=True, choices=[('Gotowka', 'Gotowka'), ('Przelew', 'Przelew')], default='Przelew', max_length=10)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('total_net_amount', models.FloatField(default=0.0, null=True)),
                ('total_gross_amount', models.FloatField(default=0.0, null=True)),
                ('total_vat_amount', models.FloatField(default=0.0, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='inv.customer')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=300)),
                ('price_net', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, default='default.jpg', upload_to='product_photo')),
                ('slug', models.SlugField(editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_fee', models.FloatField(choices=[(0.23, '23%'), (0.08, '8%'), (0.05, '5%'), (0.0, '0%')], default=0.23)),
                ('product_quantity', models.PositiveIntegerField(default=0)),
                ('total_per_products', models.FloatField()),
                ('total_net', models.FloatField()),
                ('total_vat', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(through='inv.InvoiceItem', to='inv.Product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='users_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.company'),
        ),
    ]
